# Generated by Django 3.1.2 on 2020-10-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('country_iso', models.CharField(max_length=3)),
                ('lat', models.FloatField()),
                ('lang', models.FloatField()),
                ('flag', models.CharField(max_length=200)),
                ('cases', models.IntegerField()),
                ('todayCases', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('todayDeaths', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('todayRecovered', models.IntegerField()),
                ('active', models.IntegerField()),
                ('critical', models.IntegerField()),
                ('casesPerOneMillion', models.IntegerField()),
                ('deathsPerOneMillion', models.IntegerField()),
                ('tests', models.IntegerField()),
                ('testsPerOneMillion', models.IntegerField()),
                ('population', models.IntegerField()),
                ('continent', models.CharField(max_length=200)),
                ('oneCasePerPeople', models.IntegerField()),
                ('oneDeathPerPeople', models.IntegerField()),
                ('oneTestPerPeople', models.IntegerField()),
                ('activePerOneMillion', models.FloatField()),
                ('recoveredPerOneMillion', models.FloatField()),
                ('criticalPerOneMillion', models.FloatField()),
            ],
        ),
    ]
