# Generated by Django 3.1.2 on 2020-10-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='active',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='activePerOneMillion',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='cases',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='casesPerOneMillion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='critical',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='criticalPerOneMillion',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='deaths',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='deathsPerOneMillion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='lang',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='oneCasePerPeople',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='oneDeathPerPeople',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='oneTestPerPeople',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='population',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='recovered',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='recoveredPerOneMillion',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='tests',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='testsPerOneMillion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='todayCases',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='todayDeaths',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='todayRecovered',
            field=models.IntegerField(null=True),
        ),
    ]
